spring:
  application:
    name: point-client

---
server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
    hostname: point-client
    #自定义实例格式
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:@project.version@
    #自定义元数据
    metadata-map:
      point1: 1
      point2: 2
    #心跳检测间隔
    lease-renewal-interval-in-seconds: 30
    #剔除服务时间
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://SpringCloudServerA:8081/eureka
spring:
  config:
    activate:
      on-profile: pointA

---

server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
    hostname: point-client
    #自定义实例格式
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:@project.version@
    #自定义元数据
    metadata-map:
      point1: 1
      point2: 2
    #心跳检测间隔
    lease-renewal-interval-in-seconds: 30
    #剔除服务时间
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://SpringCloudServerB:8082/eureka

spring:
  config:
    activate:
      on-profile: pointB

